# Generated by Django 3.2.4 on 2021-06-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogsite', '0004_post_ttag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ttag',
            new_name='tag',
        ),
    ]
