# Generated by Django 3.2.4 on 2021-06-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogsite', '0005_rename_ttag_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(default=models.CharField(max_length=255), max_length=255),
        ),
    ]
